# Default values for zalenium.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount(Pod Count)
replicaCount: 1

# zalenium image
image:
  repository: dosel/zalenium
  tag: 3
  pullPolicy: IfNotPresent

metadata:
  namespace: digipita-test
nameOverride: ""
fullnameOverride: ""

# service discovery
service:
  type: NodePort
  sessionAffinity: None
  zalenium:
    port: 4444
    targetPort: 4444
  register:
    port: 4445
    targetPort: 4445

# resource & limit
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi

# related resource & limit
kubernetes:
  cpu_request: "1"
  cpu_limit: "2"
  memory_request: "2Gi"
  memory_limit: "2Gi"
  override_wait_time: "5m"

# zalenium config
zalenium:
  desiredContainers: "1"
  maxDockerSeleniumContainers: "2"
  sauceLabsEnabled: "false"
  browserStackEnabled: "false"
  testingBotEnabled: "false"
  startTunnel: "false"
  videoRecordingEnabled: "true"
  screenWidth: "1900"
  screenHeight: "1880"
  timeZone: "Asia/Tokyo"
  sendAnonymousUsageInfo: "true"
  debugEnabled: "true"
  logJson: "false"
  logbackConfigFilePath: "logback.xml"
  seleniumImageName: "elgalu/selenium"
  maxTestSessions: "1"
  keepOnlyFailedTests: "false"
  retentionPeriod: "3"

# volumeMount. if you don't want persistentVolume, you should comment out following section.
volumeMounts:
  - name: zalenium-data
    mountPath: /home/seluser/videos
  - name: zalenium-mounted
    mountPath: /tmp/mounted

# volume. if you don't want persistentVolume, you should comment out following section.
volumes:
  - name: zalenium-data
    persistentVolumeClaim:
      claimName: zalenium-data
  - name: zalenium-mounted
    persistentVolumeClaim:
      claimName: zalenium-mounted

# persistentVolume. if you don't want persistentVolume, you should comment out following section.
persistentVolume:
  data:
    name: zalenium-data
    accessModes: ReadWriteMany
    size: 2Gi
#    storageClass: hostpath
    storageClass: "aws-efs"
  mounted:
    name: zalenium-mounted
    accessModes: ReadWriteMany
    size: 2Gi
#    storageClass: hostpath
    storageClass: "aws-efs"

# livenessProbe. if you don't want livnessProbe, you should comment out following section.
livenessProbe:
  httpGet:
    path: "/"
    port: 4444
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 60
  successThreshold: 1
  failureThreshold: 5

# readinessProbe. if you don't want readinessProbe, you should comment out following section.
readinessProbe:
  httpGet:
    path: "/grid/console"
    port: 4444
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 60
  successThreshold: 1
  failureThreshold: 5
